"""Ardour command knowledge base.

Lets the agent answer "how do I ... in Ardour?" from Ardour's own command
definitions (keybindings + menus), generated by scripts/build_ardour_kb.py,
plus a small curated FAQ for conceptual tasks that aren't a single shortcut.

macOS shortcut symbols: ⌘ Command · ⌃ Control · ⇧ Shift · ⌥ Option.
"""
import json
import re
from pathlib import Path

_DATA = Path(__file__).resolve().parent.parent / "data" / "ardour_commands.json"

# Conceptual how-tos that aren't a single keybinding. Hand-curated, concise,
# accurate to Ardour 9 default behaviour.
_FAQ = [
    ("add a new track audio midi instrument",
     "Add a track: Track menu → Add Track, Bus or VCA… (or ⌘⇧N). Choose "
     "MIDI for instruments, Audio for recordings, pick how many and an "
     "instrument, then Add."),
    ("record arm enable recording capture",
     "Record: arm a track with its round record-enable button, arm the "
     "transport with the master Record button, then press Play (Space). Audio "
     "needs an input; MIDI records from your keyboard/controller."),
    ("add plugin effect instrument insert eq reverb compressor",
     "Add a plugin: right-click a track's black processor box (top of the "
     "mixer strip, or the track header) → New Plugin → pick from the list. "
     "Drag plugins to reorder; double-click to open the editor."),
    ("tempo bpm change set",
     "Tempo: double-click the tempo marker at the start of the ruler, or use "
     "the Tempo field in the secondary clock. Stem can also set it for you."),
    ("export render bounce mixdown audio wav",
     "Export: Session menu → Export → Export to Audio File(s)… Set the range, "
     "format and path, then Export. Stem export of stems is on the roadmap."),
    ("loop region playback",
     "Loop: select a range, then press the Loop button or set the loop range "
     "and toggle loop play. The transport repeats that range."),
    ("undo redo mistake",
     "Undo is ⌘Z, Redo is ⌘⇧Z. Stem's own actions are also undoable."),
    ("save session project",
     "Save the session with ⌘S (Session → Save). Snapshots (Session → "
     "Snapshot) keep alternate versions."),
    ("metronome click track",
     "Metronome: toggle the click with the Metronome button in the transport "
     "bar (or the keybinding shown for 'Toggle Click')."),
    ("quantize timing align notes grid",
     "Quantize MIDI: select notes in the MIDI editor → right-click → "
     "Quantize, or use the Quantize action; set the grid you want to snap to."),
]


class _KB:
    def __init__(self):
        self.commands = []
        try:
            self.commands = json.loads(_DATA.read_text())
        except Exception:
            self.commands = []

    @staticmethod
    def _tokens(s: str):
        return set(re.findall(r"[a-z0-9]+", s.lower()))

    def search(self, query: str, limit: int = 8):
        q = self._tokens(query)
        if not q:
            return {"commands": [], "tips": []}

        scored = []
        for c in self.commands:
            hay = f"{c['label']} {c['action']} {c['group']}".lower()
            htok = self._tokens(hay)
            score = len(q & htok)
            # boost when the whole query phrase appears in the label
            if query.strip().lower() in c["label"].lower():
                score += 3
            if score > 0:
                scored.append((score, c))
        scored.sort(key=lambda x: (-x[0], x[1]["label"]))
        cmds = [{
            "label": c["label"],
            "shortcut_mac": c["key_mac"],
            "shortcut": c["key"],
            "menu_group": c["group"],
        } for _, c in scored[:limit]]

        tips = []
        for keys, answer in _FAQ:
            if q & self._tokens(keys):
                tips.append(answer)

        return {"commands": cmds, "tips": tips[:4]}


kb = _KB()
